### ISSUE TITLE
W-Shackleton, 

### ISSUE THREAD

**Issue by michaelabidi** [w-shackleton/android-netspoof#12] opened 2014-07-19 08:55 UTC
Im using your android netspoof app dinds today, but no matter what i do (as an example redirect a website to fake news)

It keeps sending all devices to blueballfixed.ytmnd.com 
(Happens with all spoofing options)

Best Reguards,
Michael

**Comment by w-shackleton** [comment] 2015-01-06 17:36
Duplicate of #21 - will look into it.

**Closed by w-shackleton** 2015-01-06 17:36 UTC
