### ISSUE TITLE
Does not work on Lollipop

### ISSUE THREAD

**Issue by iKlem** [w-shackleton/android-netspoof#22] opened 2014-12-24 17:18 UTC
Hi.
I use Network spoofer 2.0.2 on my Nexus 5 with Android 5.0.1.
The application start, I can select a spoof and someone to spoof. But when I touch the "Start" button, it stuck on the redirect thing and wait. Link to image : http://imgur.com/K0H3ZpK

**Comment by w-shackleton** [comment] 2015-01-06 17:34
I have just released [Network Spoofer 2.1.0](https://github.com/w-shackleton/android-netspoof/releases/tag/2.1.0) - please can you check whether this issue still happens with this new version (the app will prompt to update).

**Comment by iKlem** [comment] 2015-01-06 17:46
I have update the app. But after the Su prompt, it don't scan and go back to the list. And when I try to manually scan the "Scanning for device" appear quickly and no device appeared. 
Sorry for my English.

**Comment by w-shackleton** [comment] 2015-03-01 22:08
I've just released [Network Spoofer 2.2.0](https://github.com/w-shackleton/android-netspoof/releases/tag/2.2.0) - does this fix it?

**Comment by iKlem** [comment] 2015-03-01 22:18
I've download it and when I use any spoof it close activity by activity backward, close the app and crashed all my phone. That was funny to see :)

**Comment by w-shackleton** [comment] 2015-03-02 11:26
Thanks, I'll see if I can reproduce. Which screen does it crash at - how many of these do you get through?
* Welcome screen
* Select spoof
* Select target network
* Select victim
* Start / Stop screen
* Start / Stop screen (having pressed start)

**Comment by iKlem** [comment] 2015-03-02 17:24
Well, i can't reproduce what i say before. I don't know how i manage to do that, but i remember it :  i have the Welcome screen, the Select spoof, the select target, and now he keeps searching for victims (see this : 
![screenshot_2015-03-02-18-20-04 1](https://cloud.githubusercontent.com/assets/1726412/6446153/455f18b0-c109-11e4-977b-5356afd8f71e.png)
).
I tried to enter an IP and it works. I have tested only the Blue Ball Machine Spoof.

**Comment by w-shackleton** [comment] 2015-03-02 17:40
Interesting - I'll investigate. Do you have a static IP on your phone?

**Comment by iKlem** [comment] 2015-03-02 17:43
I use DHCP option on my wifi

**Comment by AdamSayar** [comment] 2015-03-04 03:01
Hello, I am an owner of a rooted Nexus 5 on Lollipop 5.0.1-2 and would like to use network spoofed very much. I have been following this and am in the same situation as iKlem. My phone has crashed twice with Network Spoofer 2.2, though it was working before on one spoof where I got the link for the redirected website to show up on my iPad. The website wouldn't load though for any device in the house. I am very new to rooting, and have had my phone rooted for one week. Thank you for any help, and nice work on the app!

**Comment by w-shackleton** [comment] 2015-03-06 14:34
Are you running AOSP or a custom firmware?

On my test device I'm running Cyanogenmod and it works - I'll flash AOSP and try with that.

**Comment by mnbvcxzl90** [comment] 2015-03-06 14:38
I would just like to add that the app works fine on my lollipop powered htc one (m8) using MaximusHD, so might not be lollipop's fault...

**Comment by w-shackleton** [comment] 2015-03-06 14:39
Ooh nice :smiley: I'll do some further investigation then

**Comment by mnbvcxzl90** [comment] 2015-03-06 14:41
Yeah, at first I thought it was not working but when I tested it yesterday on my network it was functioning perfectly.

**Comment by mnbvcxzl90** [comment] 2015-03-06 14:42
Seems to be hit or miss depending on network, works fine on mine and a few others, but seems to not work on a friend's.

**Comment by w-shackleton** [comment] 2015-03-06 14:43
One bug I had in the past was Network Spoofer only worked for IP addresses where the first octet was <128 (eg. 10.0.0.0/24 works, 192.168.1.0/24 doesn't) - is this the case for you?

**Comment by mnbvcxzl90** [comment] 2015-03-06 14:45
Seems to be, I have not payed attention to the ip addresses but my network follows 10.0.0.0/24 and works, I will look next time.

**Comment by AdamSayar** [comment] 2015-03-06 15:14
Ok I'm not sure about any of this, I am not at my home network or able to
use my app right now. I'm running a ROM called PureWhite.

**Comment by iKlem** [comment] 2015-03-06 16:48
"Are you running AOSP or a custom firmware?

On my test device I'm running Cyanogenmod and it works - I'll flash AOSP and try with that."

I'm on AOSP.

**Comment by mnbvcxzl90** [comment] 2015-03-06 19:37
So a bug I am facing that I just noticed is clicking "preferences" crashes the app.

**Comment by w-shackleton** [comment] 2015-03-06 22:36
[Fix for preferences crashing](https://github.com/w-shackleton/android-netspoof/pull/60)

**Comment by mnbvcxzl90** [comment] 2015-03-06 22:42
Was the app updated with the fix :o?

**Comment by w-shackleton** [comment] 2015-03-06 22:43
Not yet but code is committed - the next release will have fixed preferences.

**Comment by mnbvcxzl90** [comment] 2015-03-06 22:43
Glad to hear it, any ideas as to the whole only works on some networks issue?

**Comment by w-shackleton** [comment] 2015-03-06 22:56
Currently writing some unit tests for the code that deals with IP addresses to make sure it all behaves in both environments.

**Comment by w-shackleton** [comment] 2015-03-08 15:59
^that should fix NS running on lollipop. I'll next investigate the victim selector not working.

**Comment by AdamSayar** [comment] 2015-03-08 16:22
I see that network spoofer is working fully on lollipop now due to your post, but how do I download an apk for the completely working one?

**Comment by AdamSayar** [comment] 2015-03-08 16:30
Please anyone respond as quick as you can and thank you very much for your time.

**Comment by w-shackleton** [comment] 2015-03-08 16:32
The code is committed, but not yet released. After making a few more changes I'll make a release tonight.

**Comment by AdamSayar** [comment] 2015-03-08 16:38
OK thank you. So you've made the code, and will release a new apk of network spoofer tonight. Good. Will it be available right here?

**Comment by w-shackleton** [comment] 2015-03-08 21:36
I've just released [Network Spoofer 2.2.1](https://github.com/w-shackleton/android-netspoof/releases/tag/2.2.1) - open the app and it will prompt to update.

Please confirm if it works.

**Comment by AdamSayar** [comment] 2015-03-08 22:14
Hmm... With my nexus 5 lollipop 5.0.1-2 it seems to have worked with a friend's custom hotspot (used custom redirect to YouTube) but the website took a really long time to load. My phone crashed again and I rebooted. Trying it again on home network, no results.

**Comment by iKlem** [comment] 2015-03-08 22:21
So, I have tested 3 times and i have the same result for the 1st and the 2nd : 
1. The application start normally
2. Selection of spoof 
3. Selection of Gateway (Default)
4. Accepting the Su prompt
5. Waiting for "Scanning for devices..." (i wait 5 min approximately)
6. Pushed the "Back" button to the start
7. Selection of another spoof
8. Selection of the same Gateway
9. And wait again... 
   * With the first test, it crashes my phone
   * The second crash after the 3rd "Back and selection spoof/selection Gateway"

The 3rd test is made with the "Other" option and it worked.

**Comment by AdamSayar** [comment] 2015-03-08 22:27
Custom image just worked on a Mac, but my phone slowed down again and I decided to reboot. I think the app works, just inconsistently.

**Comment by w-shackleton** [comment] 2015-03-09 16:32
OK thanks. I'll close this issue as working on Lollipop and open new issues for the details given.

**Closed by w-shackleton** 2015-03-09 16:32 UTC

**Comment by adarshmishraqweasya** [comment] 2016-05-05 16:03
I got error in network spoofer it showing for checking log

**Comment by mcglaive22** [comment] 2017-03-17 12:49
mine's not working either .. i'm using lollipop v5.1. When I start spoofing I notice  this Iptables failed at the log and after stopping it network spoofer closes.

**Comment by AbrahamSosa** [comment] 2017-05-06 20:29
Hi, i have a question... the app does it works in andriod 6.1?
